# Generated by Django 5.1.3 on 2025-01-15 11:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('requirements', models.TextField(default='')),
                ('roles', models.TextField(default='')),
                ('benefits', models.TextField(default='')),
                ('type', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('remote', 'remote'), ('onsite', 'onsite'), ('hybrid', 'hybrid')], default='remote', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('vacancy', models.IntegerField()),
                ('industry', models.CharField(max_length=250)),
                ('functional_area', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('expire_on', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_min', models.IntegerField(blank=True, null=True)),
                ('experience_max', models.IntegerField(blank=True, null=True)),
                ('candidate_location', models.JSONField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=50)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('custom_qns', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_qns', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'applied'), ('shortlisted', 'shortlisted'), ('rejected', 'rejected')], default='applied', max_length=50)),
                ('viewed', models.BooleanField(default=False)),
                ('invited', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
