# Generated by Django 5.1.3 on 2025-04-29 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('duration', models.DurationField(default=datetime.timedelta(days=30))),
                ('audience', models.CharField(choices=[('seeker', 'seeker'), ('recruiter', 'recruiter')], default='seeker', max_length=20)),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.JSONField()),
                ('posts', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(days=30))),
                ('audience', models.CharField(choices=[('seeker', 'seeker'), ('recruiter', 'recruiter')], default='seeker', max_length=20)),
                ('resdex', models.BooleanField(default=False)),
                ('rate', models.IntegerField()),
                ('feature', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
