# Generated by Django 5.1.3 on 2024-12-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed', models.BooleanField(default=False)),
                ('experiance', models.IntegerField()),
                ('job_title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('ctc', models.IntegerField()),
                ('notice_pd', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=500)),
                ('role_category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('cv', models.FileField(blank=True, null=True, upload_to='details/resume/')),
                ('skills', models.JSONField()),
                ('prefered_salary_pa', models.IntegerField()),
                ('prefered_work_loc', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.BooleanField(default=False)),
                ('education', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=200)),
                ('type_course', models.CharField(max_length=200)),
                ('specialisation', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('starting_yr', models.IntegerField()),
                ('ending_yr', models.IntegerField()),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
