# Generated by Django 5.1.3 on 2025-01-15 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.companydetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiance', models.IntegerField()),
                ('job_title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('ctc', models.IntegerField()),
                ('notice_pd', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
                ('industry', models.CharField(default='', max_length=200)),
                ('job_role', models.CharField(max_length=500)),
                ('role_category', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('ban', 'ban')], default='daily', max_length=50)),
                ('alerts', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('ban', 'ban')], default='daily', max_length=50)),
                ('mobile_notifications', models.BooleanField(default=True)),
                ('messages_recruiter', models.CharField(choices=[('immediately', 'immediately'), ('ban', 'ban')], default='immediately', max_length=50)),
                ('applications', models.CharField(choices=[('daily', 'daily'), ('ban', 'ban')], default='daily', max_length=50)),
                ('promotions', models.CharField(choices=[('daily', 'daily'), ('ban', 'ban')], default='daily', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('employed', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('nationality', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('differently_abled', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='details/resume/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='details/profile/')),
                ('skills', models.JSONField()),
                ('languages', models.JSONField(blank=True, null=True)),
                ('certificates', models.JSONField(blank=True, null=True)),
                ('projects', models.JSONField(blank=True, null=True)),
                ('prefered_salary_pa', models.IntegerField()),
                ('prefered_work_loc', models.JSONField()),
                ('total_experience_years', models.IntegerField(default=0)),
                ('total_experience_months', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=150)),
                ('employment_type', models.CharField(max_length=150)),
                ('job_shift', models.CharField(max_length=150)),
                ('job_role', models.JSONField()),
                ('pref_salary', models.IntegerField()),
                ('job_location', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=200)),
                ('type_course', models.CharField(max_length=200)),
                ('specialisation', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('starting_yr', models.IntegerField()),
                ('ending_yr', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
