# Generated by Django 5.1.3 on 2024-12-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('seeker', 'seeker'), ('recruiter', 'recruiter')], default='seeker', max_length=10),
        ),
    ]
