# Generated by Django 5.1.3 on 2025-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('logo', models.FileField(blank=True, null=True, upload_to='images/company/logo')),
                ('about', models.TextField()),
                ('website', models.URLField()),
                ('functional_area', models.CharField(max_length=250)),
                ('address', models.JSONField()),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(default='', max_length=250)),
                ('postal_code', models.CharField(max_length=6)),
                ('pan_no', models.CharField(default='', max_length=10)),
                ('gst_no', models.CharField(default='', max_length=100)),
                ('mca_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('interview_round', models.CharField(blank=True, max_length=50, null=True)),
                ('interview_status', models.CharField(default='pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('applied', 'applied'), ('reviewing', 'reviewing'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
